[package]
name = "tropo"
version = "0.3.0"
edition = "2021"
description = "A simple library to parse TcpStream data (NOT IN A USABLE STATE)"
license = "MIT"

[dependencies]
bitflags = "2.6.0"
once_cell = "1.20.2"
openssl = "0.10.68"
